# Generated by Django 2.2.6 on 2020-06-12 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0004_auto_20200612_1609'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friend',
            name='name',
        ),
        migrations.AddField(
            model_name='friend',
            name='friend_name',
            field=models.CharField(default=1, max_length=30, verbose_name='Name friend'),
            preserve_default=False,
        ),
    ]
