# Generated by Django 2.2.6 on 2020-06-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0006_auto_20200612_1639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='friend',
        ),
        migrations.AddField(
            model_name='book',
            name='friend',
            field=models.ManyToManyField(blank=True, related_name='books', to='p_library.Friend'),
        ),
    ]
