# Generated by Django 2.2.6 on 2020-06-12 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0008_auto_20200612_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='friend',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='books', to='p_library.Friend', verbose_name='Друг'),
        ),
        migrations.AlterField(
            model_name='friend',
            name='friend_name',
            field=models.CharField(max_length=30, verbose_name='Имя друга'),
        ),
    ]
