# Generated by Django 2.2.6 on 2020-06-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0012_auto_20200621_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/blog/%Y/%m/%d'),
        ),
    ]
