# Generated by Django 2.2.7 on 2020-06-28 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0014_auto_20200621_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/blog/%Y/%m/%d'),
        ),
    ]
