# Generated by Django 2.2.7 on 2020-06-28 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_library', '0016_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='age',
        ),
    ]
